apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dataplatform

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
