apiVersion: v1
kind: Secret
metadata:
  name: n8n
  labels:
    app: n8n
type: Opaque
stringData:
  # These will be populated via patches in environment overlays
  DB_POSTGRESDB_HOST: "placeholder"
  DB_POSTGRESDB_USER: "placeholder" 
  DB_POSTGRESDB_PASSWORD: "placeholder"
  encryption_key: "placeholder"