apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app: n8n
    component: main
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: n8n
    component: main
